In [11]:
import pandas as pd
import json

In [2]:
table=pd.read_html('https://ar.wikipedia.org/wiki/%D9%88%D9%84%D8%A7%D9%8A%D8%A7%D8%AA_%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1',match='الخريطة')

In [3]:
print(f'Total tables: {len(table)}')

Total tables: 1

In [4]:
df = table[0]
df.head(30)

   الخريطة رقم الولاية اسم الولاية بالحروف اللاتنية      الولاية الدوائر  \
   الخريطة رقم الولاية اسم الولاية بالحروف اللاتنية      الولاية الدوائر
0      NaN          01                        Adrar        أدرار       6
1      NaN          02                        Chlef        الشلف      13
2      NaN          03                     Laghouat      الأغواط      10
3      NaN          04               Oum El Bouaghi   أم البواقي      12
4      NaN          05                        Batna        باتنة      21
5      NaN          06                       Béjaïa        بجاية      19
6      NaN          07                       Biskra        بسكرة      10
7      NaN          08                       Béchar         بشار       6
8      NaN          09                        Blida      البليدة      10
9      NaN          10                       Bouïra      البويرة      12
10     NaN          11                  Tamanrasset      تمنراست       3
11     NaN          12                      Tébessa         تبسة      12
12     NaN          13                      Tlemcen       تلمسان      20
13     NaN          14                       Tiaret        تيارت      14
14     NaN          15                   Tizi Ouzou     تيزي وزو      21
15     NaN          16                      Algiers      الجزائر      13
16     NaN          17                       Djelfa       الجلفة      12
17     NaN          18                        Jijel         جيجل      11
18     NaN          19                        Sétif         سطيف      20
19     NaN          20                        Saïda        سعيدة       6
20     NaN          21                       Skikda       سكيكدة      13
21     NaN          22               Sidi Bel Abbès  سيدي بلعباس      15
22     NaN          23                       Annaba        عنابة       6
23     NaN          24                       Guelma        قالمة      10
24     NaN          25                  Constantine      قسنطينة       6
25     NaN          26                        Médéa       المدية      19
26     NaN          27                   Mostaganem      مستغانم      10
27     NaN          28                       M'Sila      المسيلة      15
28     NaN          29                      Mascara        معسكر      16
29     NaN          30                      Ouargla        ورقلة       6

   البلديات المساحة         السكان (2008[3]) الكثافة (2008)
   البلديات     كم2    ميل2 السكان (2008[3])         كل كم2  كل ميل2
0        16  254471   98252           261258           1.03     2.70
1        35    4795    1851          1002088         209.00   540.00
2        24   25057    9675           455602          18.00    47.00
3        29    6783    2619           621612          81.00   210.00
4        61   12192    4707          1119791          92.00   240.00
5        52    3268    1262           912577         279.00   720.00
6        27    9576    3697           547137          57.00   150.00
7        11   60850   23490           219898           3.61     9.30
8        25    1575     608          1002937         591.00  1530.00
9        45    4439    1714           695583         157.00   410.00
10        5  336839  130054           115043           0.34     0.88
11       28   14227    5493           648703          46.00   120.00
12       53    9061    3498           949135         105.00   270.00
13       42   20673    7982           846823          41.00   110.00
14       67    2956    1141          1127608         316.00   820.00
15       57    1190     460          2988145        2511.00  6500.00
16       36   66415   25643          1092184          46.00   120.00
17       28    2577     995           636948         247.00   640.00
18       60    6504    2511          1489979         229.00   590.00
19       16    6764    2612           330641          49.00   130.00
20       38    4026    1554           898680         223.00   580.00
21       52    9096    3512           604744          66.00   170.00
22       12    1439     556           609499         424.00  1100.00
23       34    4101    1583           482430         118.00   310.00
24       12    2187     844           938475         427.00  1110.00
25       64    8866    3423           819932          92.00   240.00
26       32    2175     840           737118         325.00   840.00
27       47   18718    7227           990591          53.00   140.00
28       47    5941    2294           784073         132.00   340.00
29       10  194552   75117           311337           1.60     4.10

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 11 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   (الخريطة, الخريطة)                                            1 non-null      object
 1   (رقم الولاية, رقم الولاية)                                    59 non-null     object
 2   (اسم الولاية بالحروف اللاتنية, اسم الولاية بالحروف اللاتنية)  59 non-null     object
 3   (الولاية, الولاية)                                            59 non-null     object
 4   (الدوائر, الدوائر)                                            59 non-null     object
 5   (البلديات, البلديات)                                          59 non-null     object
 6   (المساحة, كم2)                                                59 non-null     int64
 7   (المساحة, ميل2)                                               59 non-null     int64
 8   (السكان (2008[3]), السكان (2008[3]))                          59 non-null     int64
 9   (الكثافة (2008), كل كم2)                                      59 non-null     float64
 10  (الكثافة (2008), كل ميل2)                                     59 non-null     float64
dtypes: float64(2), int64(3), object(6)
memory usage: 5.2+ KB
None

In [6]:
last_row=df.tail(1)
df = df.iloc[:-1, :]

In [7]:
last_row.head()

    الخريطة رقم الولاية اسم الولاية بالحروف اللاتنية  الولاية    الدوائر  \
    الخريطة رقم الولاية اسم الولاية بالحروف اللاتنية  الولاية    الدوائر
58  المجموع     المجموع                      المجموع  المجموع  547 دائرة

      البلديات  المساحة         السكان (2008[3]) الكثافة (2008)
      البلديات      كم2    ميل2 السكان (2008[3])         كل كم2 كل ميل2
58  1541 بلدية  2381741  919595         34080030           14.0    36.0

---
---
---
# Cities


## Extract Arabic city names ("Wilayat") into a single list

In [8]:
# Extract Arabic city names ("Wilayat") into a single list
wilayat_ar = [row[3] for row in df.itertuples(index=False)]

print(wilayat_ar )
print(len(wilayat_ar) )

['أدرار', 'الشلف', 'الأغواط', 'أم البواقي', 'باتنة', 'بجاية', 'بسكرة', 'بشار', 'البليدة', 'البويرة', 'تمنراست', 'تبسة', 'تلمسان', 'تيارت', 'تيزي وزو', 'الجزائر', 'الجلفة', 'جيجل', 'سطيف', 'سعيدة', 'سكيكدة', 'سيدي بلعباس', 'عنابة', 'قالمة', 'قسنطينة', 'المدية', 'مستغانم', 'المسيلة', 'معسكر', 'ورقلة', 'وهران', 'البيض', 'إليزي', 'برج بوعريريج', 'بومرداس', 'الطارف', 'تندوف', 'تيسمسيلت', 'الوادي', 'خنشلة', 'سوق أهراس', 'تيبازة', 'ميلة', 'عين الدفلى', 'النعامة', 'عين تموشنت', 'غرداية', 'غليزان', 'تيميمون', 'برج باجي مختار', 'أولاد جلال', 'بني عباس', 'عين صالح', 'عين قزام', 'تقرت', 'جانت', 'المغير', 'المنيعة']
58


## Extract Latin city names ("Wilayat") into a single list

In [10]:
# Extract Latin city names ("Wilayat") into a single list
wilayat_en = [row[2] for row in df.itertuples(index=False)]

print(wilayat_en )
print(len(wilayat_en))

['Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouïra', 'Tamanrasset', 'Tébessa', 'Tlemcen', 'Tiaret', 'Tizi Ouzou', 'Algiers', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda', 'Sidi Bel Abbès', 'Annaba', 'Guelma', 'Constantine', 'Médéa', 'Mostaganem', "M'Sila", 'Mascara', 'Ouargla', 'Oran', 'El Bayadh', 'Illizi', 'Bordj Bou Arréridj', 'Boumerdès', 'El Taref', 'Tindouf', 'Tissemsilt', 'El Oued', 'Khenchela', 'Souk Ahras', 'Tipaza', 'Mila', 'Aïn Defla', 'Naâma', 'Aïn Témouchent', 'Ghardaïa', 'Relizane', 'Timimoun', 'Bordj Badji Mokhtar', 'Ouled Djellal', 'Béni Abbès', 'In Salah', 'Ain Guezzam', 'Touggourt', 'Djanet', "El M'Ghair", 'El Menia']
58

## Export Cities as json files

In [12]:
with open('wilayat_ar.json', 'w', encoding='utf-8') as f:
    json.dump(wilayat_ar, f, ensure_ascii=False)

In [13]:
with open('wilayat_en.json', 'w', encoding='utf-8') as f:
    json.dump(wilayat_en, f, ensure_ascii=False)